services:
  postgres:
    image: postgres:latest
    container_name: fcislolv2-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - fcislolv2-volume:/var/lib/postgresql/data

volumes:
  fcislolv2-volume:
